name: "terraform-module"
description: "terraform-module"
inputs:
  TERRAFORM_CLOUD_API_TOKEN:
    description: "TERRAFORM_CLOUD_API_TOKEN"
    required: true
  TURN_SETUP_TERRAFORM:
    description: "SKIP_SETUP_TERRAFORM"
    required: false
    default: "off"
  TERRAFORM_ACTIONS:
    description: "TERRAFORM_ACTIONS apply or destroy"
    required: true
  TERRAFORM_MODULE:
    description: "TERRAFORM_MODULE name"
    required: true
  TERRAFORM_CH_DIR:
    description: "TERRAFORM_CH_DIR name"
    required: false
    default: "/"

outputs:
  random-number:
    description: "Random number"
    value: "test111"
runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v1
      if: ${{ inputs.TURN_SETUP_TERRAFORM == 'ON'}}
      with:
        cli_config_credentials_token: ${{ inputs.TERRAFORM_CLOUD_API_TOKEN }}
    - name: "setup env and parm"
      run: |
          echo "TERRAFORM_CH_DIR: ${{inputs.TERRAFORM_CH_DIR}}"
          echo "TERRAFORM_MODULE: ${{inputs.TERRAFORM_MODULE}}"
          if [[ "${{ inputs.TERRAFORM_CH_DIR}}" ]]; then chdir="-chdir=${{ inputs.TERRAFORM_CH_DIR }}"; else echo "no TERRAFORM_CH_DIR"; fi
          echo $chdir
          echo chdir=$chdir >> $GITHUB_ENV
          if [[ "${{ inputs.TERRAFORM_MODULE}}" ]]; then target="-target=module.${{ inputs.TERRAFORM_MODULE }}"; else echo "no TERRAFORM_MODULE"; fi
          echo $target
          echo target=$target >> $GITHUB_ENV
      shell: bash
    - name: "Init Terraform"
      id: init
      run: |
        echo $chdir
        terraform $chdir init
      shell: bash

    - name: "Validate Terraform"
      id: validate
      run: terraform $chdir validate
      shell: bash

    - name: "Terraform Plan"
      id: plan
      if: ${{ inputs.TERRAFORM_ACTIONS == 'apply'}}
      run: |
        terraform $chdir plan $target -out result
      shell: bash
    - name: "Terraform destroy Plan"
      id: destroy-plan
      if: ${{  github.event.inputs.actions == 'destroy'}}
      run: terraform $chdir plan -destroy $target -out result
      shell: bash
    - name: "Terraform Apply"
      id: apply
      run: terraform $chdir apply result
      shell: bash
