apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcontribcol
spec:
  image: otel/opentelemetry-collector-contrib
  serviceAccount: otelcontribcol-sa
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
        k8s_cluster:
          collection_interval: 10s
    processors:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp, k8s_cluster]
          processors: []
          exporters: [logging]
