name: k8s-bse-apps-update
on:
  workflow_dispatch:
    inputs:
      actions:
        description: "action: plan/apply/destroy"
        default: "plan"
        required: true
      # module:
      #   description: "module name, like k8s-app-hello"
      #   required: false
      TURN_TF_MASK:
        description: "TURN_TF_MASK name"
        required: true
        default: "ON"
jobs:
  k8s-bse-apps-update:
    name: "k8s base app update"
    runs-on: ubuntu-latest
    env:
      TF_VAR_cluster_ca_certificate: ${{secrets.K8S_CLUSTER_CA_CERTIFICATE}}
      TF_VAR_config_context_auth_info: ${{secrets.K8S_CONFIG_CONTEXT_AUTH_INFO}}
      TF_VAR_k8s_host: ${{secrets.K8S_HOST}}
      TF_VAR_service_account_token: ${{secrets.K8S_SERVICE_ACCOUNT_TOKEN}}
      TF_VAR_nsg_common_internet_access_id: ${{ secrets.K8S_NSG_COMMON_INTERNET_ACCESS_ID }}
      TF_VAR_ingrss_nginx_lb_ip: ${{ secrets.K8S_INGRSS_NGINX_LB_IP }}
      TURN_TF_MASK: ${{github.event.inputs.TURN_TF_MASK}}
    steps:
      - uses: actions/checkout@v2
      - name: "echo input"
        run: |
          echo "actions: ${{github.event.inputs.actions}}"
          # echo "module: ${{github.event.inputs.module}}"

      - name: "k8s base apps update"
        id: k8s_base_app
        uses: ./.github/actions/terraform-module
        with:
          TERRAFORM_CLOUD_API_TOKEN: ${{secrets.TERRAFORM_CLOUD_API_TOKEN}}
          TURN_SETUP_TERRAFORM: 'ON'
          TERRAFORM_ACTIONS: ${{github.event.inputs.actions}}
          # TERRAFORM_MODULE: ${{github.event.inputs.module}}
          TERRAFORM_CH_DIR: "k8s-base-apps"