name: oci-k8s-apps
on:
  workflow_dispatch:
    inputs:
      actions:
        description: "action: plan/apply/destroy"
        default: "apply"
        required: true
      module:
        description: "module name, like k8s-app-hello"
        required: false
      TURN_TF_MASK:
        description: "TURN_TF_MASK name"
        required: true
        default: "ON"
      TURN_FORCE_UPDATE:
        description: "TURN_FORCE_UPDATE name"
        required: true
        default: "OFF"

jobs:
  oci-k8s-apps:
    name: "k8s install apps"
    runs-on: ubuntu-latest
    env:
      TF_VAR_cluster_ca_certificate: ${{secrets.K8S_CLUSTER_CA_CERTIFICATE}}
      TF_VAR_config_context_auth_info: ${{secrets.K8S_CONFIG_CONTEXT_AUTH_INFO}}
      TF_VAR_k8s_host: ${{secrets.K8S_HOST}}
      TF_VAR_service_account_token: ${{secrets.K8S_SERVICE_ACCOUNT_TOKEN}}
      TURN_TF_MASK: ${{github.event.inputs.TURN_TF_MASK}}

    steps:
      - uses: actions/checkout@v2
      - name: "echo input"
        run: |
          echo "actions: ${{github.event.inputs.actions}}"
          echo "module: ${{github.event.inputs.module}}"
          echo "TURN_TF_MASK: ${{github.event.inputs.TURN_TF_MASK}}"
      - name: "destroy app"
        if: ${{ github.event.inputs.actions == 'apply' && github.event.inputs.TURN_FORCE_UPDATE == 'ON' && github.event.inputs.module}}
        id: terraform_module
        uses: ./.github/actions/terraform-module
        with:
          TERRAFORM_CLOUD_API_TOKEN: ${{secrets.TERRAFORM_CLOUD_API_TOKEN}}
          TURN_SETUP_TERRAFORM: 'ON'
          TERRAFORM_ACTIONS: 'destroy'
          TERRAFORM_MODULE: ${{github.event.inputs.module}}
          TERRAFORM_CH_DIR: "k8s-apps"
      - name: "Install k8s apps"
        id: terraform_module
        uses: ./.github/actions/terraform-module
        with:
          TERRAFORM_CLOUD_API_TOKEN: ${{secrets.TERRAFORM_CLOUD_API_TOKEN}}
          TURN_SETUP_TERRAFORM: 'ON'
          TERRAFORM_ACTIONS: ${{github.event.inputs.actions}}
          TERRAFORM_MODULE: ${{github.event.inputs.module}}
          TERRAFORM_CH_DIR: "k8s-apps"
